# Generated by Django 5.2 on 2025-05-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Aktualnosci',
        ),
    ]
