# Generated by Django 5.2 on 2025-05-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0006_oferta_pozycja'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta_pozycja',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
