# Generated by Django 5.2 on 2025-05-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0008_remove_oferta_pozycja_oferta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Oferta_Pozycja',
        ),
    ]
