# Generated by Django 5.2 on 2025-05-06 16:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0009_delete_oferta_pozycja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta_Pozycja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=255)),
                ('opis', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('obrazek', models.ImageField(blank=True, null=True, upload_to='oferta/podstrony/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Oferta - podstrona',
                'verbose_name_plural': 'Oferta - podstrony',
            },
        ),
    ]
