# Generated by Django 5.2 on 2025-05-06 17:17

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0010_oferta_pozycja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cennik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, max_length=255, null=True, upload_to='cennik/')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Cennik',
                'verbose_name_plural': 'Cennik',
            },
        ),
        migrations.AlterModelOptions(
            name='oferta_pozycja',
            options={'verbose_name': 'Oferta: Podstrona', 'verbose_name_plural': 'Oferta: Podstrony'},
        ),
    ]
