# Generated by Django 5.2 on 2025-05-06 17:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0011_cennik_alter_oferta_pozycja_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cennik',
            old_name='content',
            new_name='nazwa',
        ),
        migrations.RenameField(
            model_name='cennik',
            old_name='images',
            new_name='zdjecia',
        ),
        migrations.AddField(
            model_name='cennik',
            name='opis',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
