# Generated by Django 5.2 on 2025-05-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0012_rename_content_cennik_nazwa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cennik',
            name='nazwa',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
