# Generated by Django 5.2 on 2025-05-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0013_alter_cennik_nazwa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cennik',
            name='nazwa',
        ),
    ]
