# Generated by Django 5.2 on 2025-05-06 20:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0015_alter_aktualnosci_content_alter_cennik_opis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktualnosci',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cennik',
            name='opis',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='o_nas',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oferta_pozycja',
            name='opis',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
