# Generated by Django 5.2 on 2025-05-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0016_alter_aktualnosci_content_alter_cennik_opis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktualnosci',
            name='plik',
            field=models.FileField(blank=True, null=True, upload_to='aktualnosci/pliki/'),
        ),
    ]
