# Generated by Django 5.2 on 2025-05-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0017_aktualnosci_plik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('plik', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
