# Generated by Django 5.2 on 2025-05-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0018_plik'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oferta_pozycja',
            options={'verbose_name': 'Oferta: Podstrona', 'verbose_name_plural': 'Oferta: Pozycje'},
        ),
        migrations.AlterModelOptions(
            name='plik',
            options={'verbose_name': 'Plik', 'verbose_name_plural': 'Pliki'},
        ),
        migrations.RenameField(
            model_name='aktualnosci',
            old_name='date_posted',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='aktualnosci',
            old_name='plik',
            new_name='pliki',
        ),
        migrations.RenameField(
            model_name='aktualnosci',
            old_name='content',
            new_name='tekst',
        ),
        migrations.RenameField(
            model_name='aktualnosci',
            old_name='title',
            new_name='tytul',
        ),
        migrations.RenameField(
            model_name='aktualnosci',
            old_name='images',
            new_name='zdjecia',
        ),
        migrations.RenameField(
            model_name='cennik',
            old_name='date_posted',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='cennik',
            old_name='opis',
            new_name='tekst',
        ),
        migrations.RenameField(
            model_name='cennik',
            old_name='title',
            new_name='tytul',
        ),
        migrations.RenameField(
            model_name='galeria',
            old_name='date_posted',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='galeria',
            old_name='content',
            new_name='tekst',
        ),
        migrations.RenameField(
            model_name='galeria',
            old_name='title',
            new_name='tytul',
        ),
        migrations.RenameField(
            model_name='galeria',
            old_name='images',
            new_name='zdjecia',
        ),
        migrations.RenameField(
            model_name='kontakt',
            old_name='date_posted',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='kontakt',
            old_name='content',
            new_name='tekst',
        ),
        migrations.RenameField(
            model_name='kontakt',
            old_name='title',
            new_name='tytul',
        ),
        migrations.RenameField(
            model_name='kontakt',
            old_name='images',
            new_name='zdjecia',
        ),
        migrations.RenameField(
            model_name='o_nas',
            old_name='date_posted',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='o_nas',
            old_name='content',
            new_name='tekst',
        ),
        migrations.RenameField(
            model_name='o_nas',
            old_name='title',
            new_name='tytul',
        ),
        migrations.RenameField(
            model_name='o_nas',
            old_name='images',
            new_name='zdjecia',
        ),
        migrations.RenameField(
            model_name='oferta',
            old_name='date_posted',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='oferta',
            old_name='content',
            new_name='tekst',
        ),
        migrations.RenameField(
            model_name='oferta',
            old_name='title',
            new_name='tytul',
        ),
        migrations.RenameField(
            model_name='oferta',
            old_name='images',
            new_name='zdjecia',
        ),
        migrations.AddField(
            model_name='cennik',
            name='pliki',
            field=models.FileField(blank=True, null=True, upload_to='cennik/pliki/'),
        ),
        migrations.AddField(
            model_name='galeria',
            name='pliki',
            field=models.FileField(blank=True, null=True, upload_to='galeria/pliki/'),
        ),
        migrations.AddField(
            model_name='kontakt',
            name='pliki',
            field=models.FileField(blank=True, null=True, upload_to='kontakt/pliki/'),
        ),
        migrations.AddField(
            model_name='o_nas',
            name='pliki',
            field=models.FileField(blank=True, null=True, upload_to='o_nas/pliki/'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='pliki',
            field=models.FileField(blank=True, null=True, upload_to='oferta/pliki/'),
        ),
        migrations.AddField(
            model_name='oferta_pozycja',
            name='pliki',
            field=models.FileField(blank=True, null=True, upload_to='oferta/pozycje/pliki/'),
        ),
        migrations.AlterField(
            model_name='oferta_pozycja',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='oferta/pozycje/'),
        ),
    ]
