# Generated by Django 5.2 on 2025-05-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0019_alter_oferta_pozycja_options_alter_plik_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=100, verbose_name='Telefon')),
                ('mail', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('adres', models.CharField(max_length=255, verbose_name='Adres')),
            ],
            options={
                'verbose_name': 'Stopka',
                'verbose_name_plural': 'Stopka',
            },
        ),
    ]
