# Generated by Django 5.2 on 2025-05-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0020_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='adres',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='mail',
            field=models.EmailField(blank=True, max_length=1000, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='tel',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Telefon'),
        ),
    ]
