# Generated by Django 5.2 on 2025-05-08 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0021_alter_footer_adres_alter_footer_mail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sekcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
                ('tekst', models.TextField()),
                ('pliki', models.FileField(blank=True, null=True, upload_to='pliki/')),
                ('zdjecia', models.ImageField(blank=True, max_length=255, null=True, upload_to='zdjecia/')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('styl', models.CharField(choices=[('default', 'Domyślny'), ('img_left', 'Obrazek po lewej'), ('img_right', 'Obrazek po prawej'), ('img_top', 'Obrazek na górze')], default='default', max_length=30)),
                ('kolejnosc', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['kolejnosc'],
            },
        ),
    ]
