# Generated by Django 5.2 on 2025-05-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0023_alter_sekcja_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sekcja',
            name='przycisk',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sekcja',
            name='tekst',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sekcja',
            name='tytul',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
