# Generated by Django 5.2 on 2025-05-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0024_sekcja_przycisk_alter_sekcja_tekst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sekcja',
            name='przycisk',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
