# Generated by Django 5.2 on 2025-05-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0025_alter_sekcja_przycisk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sekcja',
            name='styl',
            field=models.CharField(choices=[('default', 'Domyślny'), ('img_left', 'Obrazek po lewej'), ('img_right', 'Obrazek po prawej'), ('img_top', 'Obrazek na górze'), ('tiles', 'Kafelek')], default='default', max_length=90),
        ),
    ]
