# Generated by Django 5.2 on 2025-05-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0026_alter_sekcja_styl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sekcja',
            name='styl',
            field=models.CharField(choices=[('default', 'Domyślny'), ('img-left', 'Obrazek po lewej'), ('img-right', 'Obrazek po prawej'), ('img-top', 'Obrazek na górze'), ('tiles', 'Kafelek')], default='default', max_length=90),
        ),
    ]
