# Generated by Django 5.2 on 2025-05-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0027_alter_sekcja_styl'),
    ]

    operations = [
        migrations.AddField(
            model_name='sekcja',
            name='tekst_pliku',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
