# Generated by Django 5.2 on 2025-05-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0029_home_delete_plik_delete_sekcja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta_pozycja',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Adres'),
        ),
    ]
