# Generated by Django 5.2 on 2025-05-09 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0030_alter_oferta_pozycja_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Oferta_Pozycja',
        ),
    ]
