# Generated by Django 5.2 on 2025-05-09 15:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0031_delete_oferta_pozycja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktualnosci',
            name='tekst',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cennik',
            name='tekst',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='tekst',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='tekst',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='tekst',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='o_nas',
            name='tekst',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tekst',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
    ]
