# Generated by Django 5.2 on 2025-05-09 17:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0032_alter_aktualnosci_tekst_alter_cennik_tekst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktualnosci',
            name='nazwa',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cennik',
            name='nazwa',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='galeria',
            name='nazwa',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='nazwa',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='kontakt',
            name='nazwa',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='o_nas',
            name='nazwa',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='nazwa',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='aktualnosci',
            name='tekst',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60000, null=True),
        ),
        migrations.AlterField(
            model_name='cennik',
            name='tekst',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60000, null=True),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='tekst',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60000, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='tekst',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60000, null=True),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='tekst',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60000, null=True),
        ),
        migrations.AlterField(
            model_name='o_nas',
            name='tekst',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60000, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tekst',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60000, null=True),
        ),
    ]
