# Generated by Django 5.2 on 2025-05-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0033_aktualnosci_nazwa_cennik_nazwa_galeria_nazwa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktualnosci',
            name='nazwa',
        ),
        migrations.RemoveField(
            model_name='cennik',
            name='nazwa',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='nazwa',
        ),
        migrations.RemoveField(
            model_name='home',
            name='nazwa',
        ),
        migrations.RemoveField(
            model_name='kontakt',
            name='nazwa',
        ),
        migrations.RemoveField(
            model_name='o_nas',
            name='nazwa',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='nazwa',
        ),
    ]
