# Generated by Django 5.2 on 2025-05-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0034_remove_aktualnosci_nazwa_remove_cennik_nazwa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aktualnosci',
            old_name='tytul',
            new_name='nazwa',
        ),
        migrations.RenameField(
            model_name='cennik',
            old_name='tytul',
            new_name='nazwa',
        ),
        migrations.RenameField(
            model_name='galeria',
            old_name='tytul',
            new_name='nazwa',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='tytul',
            new_name='nazwa',
        ),
        migrations.RenameField(
            model_name='kontakt',
            old_name='tytul',
            new_name='nazwa',
        ),
        migrations.RenameField(
            model_name='o_nas',
            old_name='tytul',
            new_name='nazwa',
        ),
        migrations.RenameField(
            model_name='oferta',
            old_name='tytul',
            new_name='nazwa',
        ),
    ]
