# Generated by Django 5.2 on 2025-05-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0035_rename_tytul_aktualnosci_nazwa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktualnosci',
            name='tytul',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cennik',
            name='tytul',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='galeria',
            name='tytul',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='tytul',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='kontakt',
            name='tytul',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='o_nas',
            name='tytul',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='tytul',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
