# Generated by Django 5.2 on 2025-05-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0037_alter_aktualnosci_data_alter_cennik_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktualnosci',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cennik',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='o_nas',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
