# Generated by Django 5.2 on 2025-05-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0040_alter_aktualnosci_styl_alter_cennik_styl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktualnosci',
            name='styl',
            field=models.CharField(choices=[('default', 'Tekst, zwykły'), ('default-j', 'Tekst, wyjustowany'), ('default-c', 'Tekst, wycentrowany'), ('wide-panel', 'Tekst, szeroki panel'), ('img-left-s', 'Obrazek z lewej, mały'), ('img-left-m', 'Obrazek z lewej, średni'), ('img-left-l', 'Obrazek z lewej, duży'), ('img-right-s', 'Obrazek z prawej, mały'), ('img-right-m', 'Obrazek z prawej, średni'), ('img-right-l', 'Obrazek z prawej, duży'), ('img-top', 'Obrazek na górze'), ('img-bot', 'Obrazek na dole'), ('img-bot-xl', 'Obrazek na dole, XL')], default='default', max_length=90),
        ),
        migrations.AlterField(
            model_name='cennik',
            name='styl',
            field=models.CharField(choices=[('default', 'Tekst, zwykły'), ('default-j', 'Tekst, wyjustowany'), ('default-c', 'Tekst, wycentrowany'), ('wide-panel', 'Tekst, szeroki panel'), ('img-left-s', 'Obrazek z lewej, mały'), ('img-left-m', 'Obrazek z lewej, średni'), ('img-left-l', 'Obrazek z lewej, duży'), ('img-right-s', 'Obrazek z prawej, mały'), ('img-right-m', 'Obrazek z prawej, średni'), ('img-right-l', 'Obrazek z prawej, duży'), ('img-top', 'Obrazek na górze'), ('img-bot', 'Obrazek na dole'), ('img-bot-xl', 'Obrazek na dole, XL')], default='default', max_length=90),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='styl',
            field=models.CharField(choices=[('default', 'Tekst, zwykły'), ('default-j', 'Tekst, wyjustowany'), ('default-c', 'Tekst, wycentrowany'), ('wide-panel', 'Tekst, szeroki panel'), ('img-left-s', 'Obrazek z lewej, mały'), ('img-left-m', 'Obrazek z lewej, średni'), ('img-left-l', 'Obrazek z lewej, duży'), ('img-right-s', 'Obrazek z prawej, mały'), ('img-right-m', 'Obrazek z prawej, średni'), ('img-right-l', 'Obrazek z prawej, duży'), ('img-top', 'Obrazek na górze'), ('img-bot', 'Obrazek na dole'), ('img-bot-xl', 'Obrazek na dole, XL')], default='default', max_length=90),
        ),
        migrations.AlterField(
            model_name='home',
            name='styl',
            field=models.CharField(choices=[('default', 'Tekst, zwykły'), ('default-j', 'Tekst, wyjustowany'), ('default-c', 'Tekst, wycentrowany'), ('wide-panel', 'Tekst, szeroki panel'), ('img-left-s', 'Obrazek z lewej, mały'), ('img-left-m', 'Obrazek z lewej, średni'), ('img-left-l', 'Obrazek z lewej, duży'), ('img-right-s', 'Obrazek z prawej, mały'), ('img-right-m', 'Obrazek z prawej, średni'), ('img-right-l', 'Obrazek z prawej, duży'), ('img-top', 'Obrazek na górze'), ('img-bot', 'Obrazek na dole'), ('img-bot-xl', 'Obrazek na dole, XL')], default='default', max_length=90),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='styl',
            field=models.CharField(choices=[('default', 'Tekst, zwykły'), ('default-j', 'Tekst, wyjustowany'), ('default-c', 'Tekst, wycentrowany'), ('wide-panel', 'Tekst, szeroki panel'), ('img-left-s', 'Obrazek z lewej, mały'), ('img-left-m', 'Obrazek z lewej, średni'), ('img-left-l', 'Obrazek z lewej, duży'), ('img-right-s', 'Obrazek z prawej, mały'), ('img-right-m', 'Obrazek z prawej, średni'), ('img-right-l', 'Obrazek z prawej, duży'), ('img-top', 'Obrazek na górze'), ('img-bot', 'Obrazek na dole'), ('img-bot-xl', 'Obrazek na dole, XL')], default='default', max_length=90),
        ),
        migrations.AlterField(
            model_name='o_nas',
            name='styl',
            field=models.CharField(choices=[('default', 'Tekst, zwykły'), ('default-j', 'Tekst, wyjustowany'), ('default-c', 'Tekst, wycentrowany'), ('wide-panel', 'Tekst, szeroki panel'), ('img-left-s', 'Obrazek z lewej, mały'), ('img-left-m', 'Obrazek z lewej, średni'), ('img-left-l', 'Obrazek z lewej, duży'), ('img-right-s', 'Obrazek z prawej, mały'), ('img-right-m', 'Obrazek z prawej, średni'), ('img-right-l', 'Obrazek z prawej, duży'), ('img-top', 'Obrazek na górze'), ('img-bot', 'Obrazek na dole'), ('img-bot-xl', 'Obrazek na dole, XL')], default='default', max_length=90),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='styl',
            field=models.CharField(choices=[('default', 'Tekst, zwykły'), ('default-j', 'Tekst, wyjustowany'), ('default-c', 'Tekst, wycentrowany'), ('wide-panel', 'Tekst, szeroki panel'), ('img-left-s', 'Obrazek z lewej, mały'), ('img-left-m', 'Obrazek z lewej, średni'), ('img-left-l', 'Obrazek z lewej, duży'), ('img-right-s', 'Obrazek z prawej, mały'), ('img-right-m', 'Obrazek z prawej, średni'), ('img-right-l', 'Obrazek z prawej, duży'), ('img-top', 'Obrazek na górze'), ('img-bot', 'Obrazek na dole'), ('img-bot-xl', 'Obrazek na dole, XL')], default='default', max_length=90),
        ),
    ]
