# Generated by Django 5.2.1 on 2025-05-11 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0048_alter_aktualnosci_options_alter_cennik_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aktualnosci',
            options={'verbose_name': 'aktualności', 'verbose_name_plural': 'aktualności'},
        ),
        migrations.AlterModelOptions(
            name='cennik',
            options={'verbose_name': 'cennik', 'verbose_name_plural': 'cennik'},
        ),
        migrations.AlterModelOptions(
            name='galeria',
            options={'verbose_name': 'galeria', 'verbose_name_plural': 'galeria'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'strona domowa', 'verbose_name_plural': 'strona domowa'},
        ),
        migrations.AlterModelOptions(
            name='kontakt',
            options={'verbose_name': 'kontakt', 'verbose_name_plural': 'kontakt'},
        ),
        migrations.AlterModelOptions(
            name='o_nas',
            options={'verbose_name': 'o nas', 'verbose_name_plural': 'o nas'},
        ),
        migrations.AlterModelOptions(
            name='oferta',
            options={'verbose_name': 'oferta', 'verbose_name_plural': 'oferta'},
        ),
    ]
