# Generated by Django 5.2.1 on 2025-05-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0049_alter_aktualnosci_options_alter_cennik_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktualnosci',
            name='kolor',
            field=models.CharField(choices=[('kol-bialy', 'Biały'), ('kol-szary', 'Szary'), ('kol-niebieski', 'Niebieski'), ('kol-zielony', 'Zielony'), ('kol-rozowy', 'Różowy')], default='kol-bialy', max_length=90),
        ),
        migrations.AlterField(
            model_name='cennik',
            name='kolor',
            field=models.CharField(choices=[('kol-bialy', 'Biały'), ('kol-szary', 'Szary'), ('kol-niebieski', 'Niebieski'), ('kol-zielony', 'Zielony'), ('kol-rozowy', 'Różowy')], default='kol-bialy', max_length=90),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='kolor',
            field=models.CharField(choices=[('kol-bialy', 'Biały'), ('kol-szary', 'Szary'), ('kol-niebieski', 'Niebieski'), ('kol-zielony', 'Zielony'), ('kol-rozowy', 'Różowy')], default='kol-bialy', max_length=90),
        ),
        migrations.AlterField(
            model_name='home',
            name='kolor',
            field=models.CharField(choices=[('kol-bialy', 'Biały'), ('kol-szary', 'Szary'), ('kol-niebieski', 'Niebieski'), ('kol-zielony', 'Zielony'), ('kol-rozowy', 'Różowy')], default='kol-bialy', max_length=90),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='kolor',
            field=models.CharField(choices=[('kol-bialy', 'Biały'), ('kol-szary', 'Szary'), ('kol-niebieski', 'Niebieski'), ('kol-zielony', 'Zielony'), ('kol-rozowy', 'Różowy')], default='kol-bialy', max_length=90),
        ),
        migrations.AlterField(
            model_name='o_nas',
            name='kolor',
            field=models.CharField(choices=[('kol-bialy', 'Biały'), ('kol-szary', 'Szary'), ('kol-niebieski', 'Niebieski'), ('kol-zielony', 'Zielony'), ('kol-rozowy', 'Różowy')], default='kol-bialy', max_length=90),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='kolor',
            field=models.CharField(choices=[('kol-bialy', 'Biały'), ('kol-szary', 'Szary'), ('kol-niebieski', 'Niebieski'), ('kol-zielony', 'Zielony'), ('kol-rozowy', 'Różowy')], default='kol-bialy', max_length=90),
        ),
    ]
