# Generated by Django 5.2.1 on 2025-05-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0050_alter_aktualnosci_kolor_alter_cennik_kolor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='tel',
            new_name='phone',
        ),
    ]
