# Generated by Django 5.2.1 on 2025-05-25 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0052_aboutus_contact_gallery_news_offer_pricing_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Galeria', 'verbose_name_plural': 'Galeria'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Główna', 'verbose_name_plural': 'Główna'},
        ),
        migrations.AlterModelOptions(
            name='pricing',
            options={'verbose_name': 'Cennik', 'verbose_name_plural': 'Cennik'},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='color',
            field=models.CharField(choices=[('color-white', 'Biały'), ('color-gray', 'Szary'), ('color-aqua', 'Błękitny'), ('color-blue', 'Niebieski'), ('color-green', 'Zielony'), ('color-pink', 'Różowy')], default='color-white', max_length=90),
        ),
        migrations.AlterField(
            model_name='contact',
            name='color',
            field=models.CharField(choices=[('color-white', 'Biały'), ('color-gray', 'Szary'), ('color-aqua', 'Błękitny'), ('color-blue', 'Niebieski'), ('color-green', 'Zielony'), ('color-pink', 'Różowy')], default='color-white', max_length=90),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='color',
            field=models.CharField(choices=[('color-white', 'Biały'), ('color-gray', 'Szary'), ('color-aqua', 'Błękitny'), ('color-blue', 'Niebieski'), ('color-green', 'Zielony'), ('color-pink', 'Różowy')], default='color-white', max_length=90),
        ),
        migrations.AlterField(
            model_name='home',
            name='color',
            field=models.CharField(choices=[('color-white', 'Biały'), ('color-gray', 'Szary'), ('color-aqua', 'Błękitny'), ('color-blue', 'Niebieski'), ('color-green', 'Zielony'), ('color-pink', 'Różowy')], default='color-white', max_length=90),
        ),
        migrations.AlterField(
            model_name='news',
            name='color',
            field=models.CharField(choices=[('color-white', 'Biały'), ('color-gray', 'Szary'), ('color-aqua', 'Błękitny'), ('color-blue', 'Niebieski'), ('color-green', 'Zielony'), ('color-pink', 'Różowy')], default='color-white', max_length=90),
        ),
        migrations.AlterField(
            model_name='offer',
            name='color',
            field=models.CharField(choices=[('color-white', 'Biały'), ('color-gray', 'Szary'), ('color-aqua', 'Błękitny'), ('color-blue', 'Niebieski'), ('color-green', 'Zielony'), ('color-pink', 'Różowy')], default='color-white', max_length=90),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='color',
            field=models.CharField(choices=[('color-white', 'Biały'), ('color-gray', 'Szary'), ('color-aqua', 'Błękitny'), ('color-blue', 'Niebieski'), ('color-green', 'Zielony'), ('color-pink', 'Różowy')], default='color-white', max_length=90),
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=500, null=True, verbose_name='Opis zdjęcia')),
                ('order', models.PositiveIntegerField(default=0)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tusi.gallery')),
            ],
            options={
                'verbose_name': 'Zdjęcie w galerii',
                'verbose_name_plural': 'Zdjęcia w galerii',
                'ordering': ['order'],
            },
        ),
    ]
