# Generated by Django 5.2.1 on 2025-05-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tusi', '0053_alter_gallery_options_alter_home_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryItem',
        ),
    ]
